### ISSUE TITLE
编解码正确性似乎有点问题，取出来的文件会少一些字节

### ISSUE THREAD

**Issue by jyi2ya** [tanyingkongxin/EvenOdd#28]
在项目根目录运行这个脚本：

```sh
#!/bin/sh

sh compile.sh
cp /usr/bin/ls ls.orig
cp ls.orig ls
cnt=0
while diff ls.orig ls; do
    ./evenodd write ls.orig 31
    rm -rf disk_9
    ./evenodd repair 1 9
    ./evenodd read ls.orig ls
    cnt=$((cnt + 1))
done
echo error detected after "$cnt" runs
```

这个脚本会重复执行以下过程：

* 以 `p=31` 存入文件 `ls`
* 毁掉第 9 个磁盘
* 修复第 9 个磁盘
* 把 `ls` 读出来，并且与原始文件比较

正常情况应该是脚本不退出，且 ls 和 ls.orig 始终一致。但是本项目中，这个脚本会在循环 1 至 2 次后退出。检查 ls 和 ls.orig 文件会发现，取出来的 ls 前面部分和 ls.orig 一致，尾部丢失了一些字节……

-----

代码跑得真的很快，谢谢大佬的分享 <3

**Comment by Yorkking** [comment]
因为你是重复编码 ls.orig 和 ls 文件，项目中并不考虑重复编码同一个文件的情况。

**Comment by Yorkking** [comment]
对于文件名为 file_name 的文件，进行 evenodd write file_name p 的时候，只会简单的往 disk_0, disk_1, disk_..., disk_{p+1}  写入 file_name_1 ，file_name_2，...，文件，然后确实没有检查 file_name_1 之类的是否存在，默认使用 open(O_APPEND) 的方式创建文件，我们只考虑了一次写入的情况，没有考虑重复写的情况。

**Comment by jyi2ya** [comment]
> 对于文件名为 file_name 的文件，进行 evenodd write file_name p 的时候，只会简单的往 disk_0, disk_1, disk_..., disk_{p+1} 写入 file_name_1 ，file_name_2，...，文件，然后确实没有检查 file_name_1 之类的是否存在，默认使用 open(O_APPEND) 的方式创建文件，我们只考虑了一次写入的情况，没有考虑重复写的情况。

哦，试了下发现确实是这样的。谢谢你！
